<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="sts2" HintPath="D:\Program Files (x86)\steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll" Private="false" />
    <Reference Include="GodotSharp" HintPath="D:\Program Files (x86)\steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll" Private="false" />
    <Reference Include="STS2-RitsuLib" HintPath="C:\Users\13586\.nuget\packages\sts2.ritsulib.compat.0.107.1\0.5.14\lib\net9.0\STS2-RitsuLib.dll" Private="false" />
  </ItemGroup>
</Project>
